---
- name: Deploy Xray with VLESS XTLS Vision
  hosts: all
  become: true
  vars:
    project_root: "/opt/xray"
  roles:
    - docker_prereqs
    - system_maintenance
    - certificates
    - xray_cleanup
    - xray_deploy
