---
- name: Deploy Xray with VLESS XTLS Vision
  hosts: all
  become: true
  vars:
    project_root: "/opt/xray"
  roles:
    - docker_prereqs
    - certificates
    - xray_config
    - docker_compose
